### ISSUE TITLE
Fingerprint settings crush (FPC)

### ISSUE THREAD

**Issue by karevn** [karevn/android_device_xiaomi_markw#11]
1. Add fingerprints
2. Remove them all
3. The settings screen will crush with 

```
10-22 22:05:04.927 E/BatteryStatsService(1236): no controller energy info supplied
10-22 22:05:04.927 E/BatteryStatsService(1236): no controller energy info supplied
10-22 22:05:05.312 E/BatteryStatsService(1236): no controller energy info supplied
10-22 22:05:05.698 W/FingerprintService(1236): Client android.os.BinderProxy@68530bf failed to respond to cancel, starting client android.os.BinderProxy@68530bf
10-22 22:05:05.698 V/FingerprintService(1236): starting client RemovalClient(android.os.BinderProxy@68530bf), initiatedByClient = false)
10-22 22:05:05.699 V/fingerprintd(851): remove(fid=526674308, gid=0)
10-22 22:05:05.699 D/fpc_fingerprint_hal(851): fpc_remove(fid=526674308 gid=0)
10-22 22:05:05.705 E/fpc_tac (851): fpc_tac_send_cmd failed with retval: 9
10-22 22:05:05.705 I/fpc_fingerprint_hal(851): do_navigation end -
10-22 22:05:05.717 D/fpc_fingerprint_hal(851): workerFunction STATE_IDLE
10-22 22:05:05.724 D/fpc_fingerprint_hal(851): indices_count 0
10-22 22:05:05.724 D/fpc_fingerprint_hal(851): fingerprint not found, notifying removed fid=526674308 gid=0
10-22 22:05:05.724 D/fingerprintd(851): onRemove(fid=526674308, gid=0)
10-22 22:05:05.724 D/fpc_fingerprint_hal(851): fpc_wait_finger_up
10-22 22:05:05.726 W/FingerprintSettings(3703): Can't find preference to remove: key_fingerprint_item_526674308
10-22 22:05:05.727 D/AndroidRuntime(3703): Shutting down VM
--------- beginning of crash
10-22 22:05:05.728 E/AndroidRuntime(3703): FATAL EXCEPTION: main
10-22 22:05:05.728 E/AndroidRuntime(3703): Process: com.android.settings, PID: 3703
10-22 22:05:05.728 E/AndroidRuntime(3703): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at com.android.settings.fingerprint.FingerprintSettings$FingerprintSettingsFragment.updateAddPreference(FingerprintSettings.java:375)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at com.android.settings.fingerprint.FingerprintSettings$FingerprintSettingsFragment.-wrap4(FingerprintSettings.java)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at com.android.settings.fingerprint.FingerprintSettings$FingerprintSettingsFragment$3.handleMessage(FingerprintSettings.java:212)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at android.os.Looper.loop(Looper.java:154)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at java.lang.reflect.Method.invoke(Native Method)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-22 22:05:05.728 E/AndroidRuntime(3703): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-22 22:05:05.733 W/ActivityManager(1236):   Force finishing activity com.android.settings/.Settings
10-22 22:05:05.741 D/fpc_fingerprint_hal(851): fpc_wait_finger_up FPC_LIB_FINGER_LOST
10-22 22:05:05.741 I/fpc_fingerprint_hal(851): workerFunction STATE_NONE (Navigation)
10-22 22:05:05.741 I/fpc_fingerprint_hal(851): do_navigation start -
10-22 22:05:05.747 E/fpc_tac (851): fpc_tac_send_cmd failed with retval: 9
10-22 22:05:05.797 I/OpenGLRenderer(1236): Initialized EGL, version 1.4
10-22 22:05:05.797 D/OpenGLRenderer(1236): Swap behavior 1
10-22 22:05:05.960 D/wpa_supplicant(2047): wlan0: Control interface command 'SIGNAL_POLL'
10-22 22:05:05.977 D/wpa_supplicant(2047): CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=48
10-22 22:05:06.245 W/ActivityManager(1236): Activity pause timeout for ActivityRecord{9765d26 u0 com.android.settings/.Settings t365 f}
10-22 22:05:06.329 W/FA      (2595): Service connection failed: jr{statusCode=SERVICE_INVALID, resolution=null, message=null}
10-22 22:05:06.330 E/FA      (2595): Failed to send current screen to service
10-22 22:05:08.471 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU0 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:08.472 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU0 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:08.472 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU0 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:08.472 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU0 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:08.473 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU2 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:08.473 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU2 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:08.473 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU2 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:08.473 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU2 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:08.474 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU1 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:08.474 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU1 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:08.474 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU1 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:08.474 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU1 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:08.475 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU3 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:08.475 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU3 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:08.475 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU3 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:08.985 D/wpa_supplicant(2047): wlan0: Control interface command 'SIGNAL_POLL'
10-22 22:05:09.006 D/wpa_supplicant(2047): CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=48
10-22 22:05:09.428 I/ActivityManager(1236): Killing 3703:com.android.settings/1000 (adj 900): crash
10-22 22:05:09.430 D/ActivityManager(1236): cleanUpApplicationRecord -- 3703
10-22 22:05:09.438 I/ActivityManager(1236): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.android.settings/.Settings (has extras)} from uid 10078 on display 0
10-22 22:05:09.446 E/ANDR-PERF-RESOURCEQS(426): Failed to apply optimization [4, 0]
10-22 22:05:09.452 E/ActivityManager(1236): applyOptionsLocked: Unknown animationType=0
10-22 22:05:09.471 I/ActivityManager(1236): Start proc 4500:com.android.settings/1000 for activity com.android.settings/.Settings
10-22 22:05:09.488 D/GraphicsStats(1236): Buffer count: 5
10-22 22:05:09.489 W/FA      (2595): Service connection failed: jr{statusCode=SERVICE_INVALID, resolution=null, message=null}
10-22 22:05:09.491 E/FA      (2595): Failed to send current screen to service
10-22 22:05:09.491 E/FA      (2595): Discarding data. Failed to send event to service
10-22 22:05:09.518 W/System  (4500): ClassLoader referenced unknown path: /system/priv-app/Settings/lib/arm64
10-22 22:05:09.571 W/AppOps  (1236): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-22 22:05:09.590 W/TileUtils(4500): Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
10-22 22:05:09.606 W/System  (4500): ClassLoader referenced unknown path: 
10-22 22:05:09.607 W/System  (4500): ClassLoader referenced unknown path: /system/priv-app/CellBroadcastReceiver/lib/arm64
10-22 22:05:09.608 D/ApplicationLoaders(4500): ignored Vulkan layer search path /system/priv-app/CellBroadcastReceiver/lib/arm64:/system/lib64:/vendor/lib64 for namespace 0x7f8e3f50f0
10-22 22:05:09.644 E/SDM     (474): QdcmXmlStorage::EnumerateModes: Host: Failed to open file.
10-22 22:05:09.645 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_0_title
10-22 22:05:09.646 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_1_title
10-22 22:05:09.646 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_2_title
10-22 22:05:09.646 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_3_title
10-22 22:05:09.647 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_4_title
10-22 22:05:09.647 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_5_title
10-22 22:05:09.647 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_6_title
10-22 22:05:09.648 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_7_title
10-22 22:05:09.648 E/ResourceUtils(4130): No resource found for live_display_color_profile_mode_8_title
10-22 22:05:09.660 D/LocalBluetoothProfileManager(4500): Adding local MAP profile
10-22 22:05:09.661 D/BluetoothMap(4500): Create BluetoothMap proxy object
10-22 22:05:09.664 D/BluetoothDun(4500): BluetoothDun() call bindService
10-22 22:05:09.667 V/NFC     (4500): this device does not have NFC support
10-22 22:05:09.668 D/LocalBluetoothProfileManager(4500): LocalBluetoothProfileManager construction complete
10-22 22:05:09.672 I/Adreno  (4500): QUALCOMM build                   : a9083cf, Iaf618d42e3
10-22 22:05:09.672 I/Adreno  (4500): Build Date                       : 03/14/17
10-22 22:05:09.672 I/Adreno  (4500): OpenGL ES Shader Compiler Version: XE031.09.00.04
10-22 22:05:09.672 I/Adreno  (4500): Local Branch                     : 
10-22 22:05:09.672 I/Adreno  (4500): Remote Branch                    : 
10-22 22:05:09.672 I/Adreno  (4500): Remote Branch                    : 
10-22 22:05:09.672 I/Adreno  (4500): Reconstruct Branch               : 
10-22 22:05:09.679 I/OpenGLRenderer(4500): Initialized EGL, version 1.4
10-22 22:05:09.680 W/TileUtils(4500): Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
10-22 22:05:09.680 D/OpenGLRenderer(4500): Swap behavior 1
10-22 22:05:09.694 I/IndexDatabaseHelper(4500): Using schema version: 115
10-22 22:05:09.695 I/IndexDatabaseHelper(4500): Index is fine
10-22 22:05:09.697 D/Index   (4500): Locale 'ru_RU' is already indexed
10-22 22:05:09.715 D/Index   (4500): Indexing locale 'ru_RU' took 7 millis
10-22 22:05:09.721 D/DashboardSummary(4500): onConditionsChanged
10-22 22:05:09.725 I/ActivityManager(1236): Displayed com.android.settings/.Settings: +273ms
10-22 22:05:09.744 D/Index   (4500): Indexing locale 'ru_RU' took 7 millis
10-22 22:05:09.755 I/ProcessStatsService(1236): Added stats: 2017-10-22-21-39-53, over +14m35s515ms
10-22 22:05:09.756 E/BatteryStatsService(1236): no controller energy info supplied
10-22 22:05:09.756 E/BatteryStatsService(1236): no controller energy info supplied
10-22 22:05:09.761 I/ProcessStatsService(1236): Added stats: 2017-10-22-19-21-36, over +2h18m2s31ms
10-22 22:05:09.778 W/ProcStatsManager(4500): No process com.android.providers.calendar/10005 for service com.android.providers.calendar.EmptyService
10-22 22:05:09.778 W/ProcStatsManager(4500): No process com.android.providers.calendar/10005 for service com.android.providers.calendar.CalendarProviderIntentService
10-22 22:05:09.778 W/ProcStatsManager(4500): No process com.android.messaging/10063 for service com.android.messaging.datamodel.action.BackgroundWorkerService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.messaging/10063 for service com.android.messaging.datamodel.action.ActionServiceImpl
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.carrierconfig/10004 for service com.android.carrierconfig.DefaultCarrierConfigService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.printspooler/10057 for service com.android.printspooler.model.PrintSpoolerService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process br.com.ctncardoso.ctncar/10069 for service br.com.ctncardoso.ctncar.notificacao.SchedulingService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.grarak.kerneladiutor/10080 for service com.grarak.kerneladiutor.services.boot.Service
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.grarak.kerneladiutor/10080 for service com.google.android.gms.measurement.AppMeasurementService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.cellbroadcastreceiver/10008 for service com.android.cellbroadcastreceiver.CellBroadcastConfigService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.opera.browser:sandboxed_process11/10079 for service org.chromium.content.app.SandboxedProcessService11
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.opera.browser:sandboxed_process12/10079 for service org.chromium.content.app.SandboxedProcessService12
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.onetimeinitializer/10018 for service com.android.onetimeinitializer.OneTimeInitializerService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.keychain/1000 for service com.android.keychain.KeyChainService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process by.bgpb.mbanking/10068 for service by.bgpb.mbanking.alarm.AlarmStartupService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.deskclock/10046 for service com.android.alarmclock.DigitalAppWidgetService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.android.exchange/10045 for service com.android.exchange.service.EasService
10-22 22:05:09.779 W/ProcStatsManager(4500): No process com.qualcomm.embms:remote/10060 for service com.qualcomm.embms.EmbmsService
10-22 22:05:12.015 D/wpa_supplicant(2047): wlan0: Control interface command 'SIGNAL_POLL'
10-22 22:05:12.036 D/wpa_supplicant(2047): CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=48
10-22 22:05:12.340 I/ActivityManager(1236): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.teslacoilsw.launcher/.NovaLauncher (has extras)} from uid 1000 on display 0
10-22 22:05:12.344 E/ANDR-PERF-RESOURCEQS(426): Failed to apply optimization [4, 0]
10-22 22:05:12.428 W/FA      (2595): Service connection failed: jr{statusCode=SERVICE_INVALID, resolution=null, message=null}
10-22 22:05:12.429 E/FA      (2595): Failed to send current screen to service
10-22 22:05:13.474 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU0 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:13.475 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU0 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:13.476 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU0 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:13.476 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU0 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:13.477 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU2 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:13.477 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU2 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:13.478 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU1 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:13.479 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU1 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:13.479 I/MSM-irqbalance(563): Decided to move IRQ186 from CPU1 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:13.480 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU1 [P:0] to CPU7 [P:1] (banned)
10-22 22:05:13.480 I/MSM-irqbalance(563): Decided to move IRQ3 from CPU3 [P:0] to CPU5 [P:1] (banned)
10-22 22:05:13.481 I/MSM-irqbalance(563): Decided to move IRQ164 from CPU3 [P:0] to CPU6 [P:1] (banned)
10-22 22:05:13.481 I/MSM-irqbalance(563): Decided to move IRQ5 from CPU3 [P:0] to CPU4 [P:1] (banned)
10-22 22:05:15.044 D/wpa_supplicant(2047): wlan0: Control interface command 'SIGNAL_POLL'
10-22 22:05:15.051 D/wpa_supplicant(2047): CTRL-DEBUG: global_ctrl_sock-sendto: sock=9 sndbuf=212992 outq=0 send_len=48
10-22 22:05:16.086 I/ActivityManager(1236): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.pluscubed.matlog.debug/com.pluscubed.logcat.ui.LogcatActivity (has extras)} from uid 10078 on display 0
10-22 22:05:16.100 E/ANDR-PERF-RESOURCEQS(426): Failed to apply optimization [4, 0]
10-22 22:05:16.156 I/ActivityManager(1236): Start proc 4543:com.pluscubed.matlog.debug/u0a81 for activity com.pluscubed.matlog.debug/com.pluscubed.logcat.ui.LogcatActivity
10-22 22:05:16.159 W/FA      (2595): Service connection failed: jr{statusCode=SERVICE_INVALID, resolution=null, message=null}
10-22 22:05:16.160 E/FA      (2595): Failed to send current screen to service
10-22 22:05:16.160 E/FA      (2595): Discarding data. Failed to send event to service
10-22 22:05:16.162 I/art     (4543): Late-enabling -Xcheck:jni
10-22 22:05:16.240 I/art     (4543): Starting a blocking GC AddRemoveAppImageSpace
10-22 22:05:16.245 W/System  (4543): ClassLoader referenced unknown path: /data/app/com.pluscubed.matlog.debug-1/lib/arm64
10-22 22:05:16.364 E/Fabric  (4543): Error dealing with settings
10-22 22:05:16.364 E/Fabric  (4543): java.lang.IllegalArgumentException: Fabric could not be initialized, API key missing from AndroidManifest.xml. Add the following tag to your Application element 
10-22 22:05:16.364 E/Fabric  (4543): 	<meta-data android:name="io.fabric.ApiKey" android:value="YOUR_API_KEY"/>
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.services.common.ApiKey.logErrorOrThrowException(ApiKey.java:110)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.services.common.ApiKey.getValue(ApiKey.java:61)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.services.settings.Settings.initialize(Settings.java:78)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:124)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:99)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
10-22 22:05:16.364 E/Fabric  (4543): 	at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-22 22:05:16.364 E/Fabric  (4543): 	at java.lang.Thread.run(Thread.java:761)

```

**Comment by psykkuno** [comment]
I'll check that out.
